#!/usr/bin/env python3
"""Generate the browser-side data-URL bundle used for file:// PNG exports."""

import base64
import json
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
ASSETS_ROOT = PROJECT_ROOT / "assets"
OUTPUT_PATH = ASSETS_ROOT / "vendor" / "asset-data.js"
MIME_TYPES = {".png": "image/png", ".ttf": "font/ttf"}

embedded_assets = {}
for path in sorted(ASSETS_ROOT.rglob("*")):
    if not path.is_file() or path.suffix.lower() not in MIME_TYPES:
        continue
    key = path.relative_to(PROJECT_ROOT).as_posix()
    encoded = base64.b64encode(path.read_bytes()).decode("ascii")
    embedded_assets[key] = f"data:{MIME_TYPES[path.suffix.lower()]};base64,{encoded}"

source = (
    "// Generated by scripts/generate_asset_data.py.\n"
    f"window.cheatsheetAssetData = {json.dumps(embedded_assets, separators=(',', ':'))};\n"
)
OUTPUT_PATH.write_text(source, encoding="utf-8")
print(f"Embedded {len(embedded_assets)} assets in {OUTPUT_PATH.relative_to(PROJECT_ROOT)}.")
